spring.application.name=mascotas
spring.datasource.url=jdbc:postgresql://localhost:5432/mascotas-data-base
spring.datasource.username=postgres
spring.datasource.password=24681012
spring.datasource.driver-class-name=org.postgresql.Driver

#Mostrar las consultas SQL
spring.jpa.show-sql=true

#Configuración para que actualize el esquema
spring.jpa.hibernate.ddl-auto=update

#Optimizar la base de datos
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
