spring.application.name=mascotas
spring.datasource.url=jdbc:postgresql://dpg-d6t28gqa214c73cagii0-a.oregon-postgres.render.com/mascotas_data_base_e3lm?sslmode=require
spring.datasource.username=mascotas_data_base_e3lm_user
spring.datasource.password=21NF7aQR1yAgSdD912RAUkpkJbMkZLhf

# 3. Configuración del Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# 4. Hibernate y SQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect